class CreateTeamStats < ActiveRecord::Migration[8.0]
  def change
    create_table :team_stats do |t|
      t.references :team, null: false, foreign_key: true
      t.references :season, null: false, foreign_key: true
      t.string :name
      t.string :position
      t.string :situation
      t.integer :games_played
      t.float :x_goals_percentage
      t.float :corsi_percentage
      t.float :fenwick_percentage
      t.float :ice_time
      t.float :x_on_goal_for
      t.float :x_goals_for
      t.float :x_rebounds_for
      t.float :x_freeze_for
      t.float :x_play_stopped_for
      t.float :x_play_continued_in_zone_for
      t.float :x_play_continued_outside_zone_for
      t.float :flurry_adjusted_x_goals_for
      t.float :score_venue_adjusted_x_goals_for
      t.float :flurry_score_venue_adjusted_x_goals_for
      t.integer :shots_on_goal_for
      t.integer :missed_shots_for
      t.integer :blocked_shot_attempts_for
      t.integer :shot_attempts_for
      t.integer :goals_for
      t.integer :rebounds_for
      t.integer :rebound_goals_for
      t.integer :freeze_for
      t.integer :play_stopped_for
      t.integer :play_continued_in_zone_for
      t.integer :play_continued_outside_zone_for
      t.integer :saved_shots_on_goal_for
      t.integer :saved_unblocked_shot_attempts_for
      t.integer :penalties_for
      t.integer :penalty_minutes_for
      t.integer :face_offs_won_for
      t.integer :hits_for
      t.integer :takeaways_for
      t.integer :giveaways_for
      t.integer :low_danger_shots_for
      t.integer :medium_danger_shots_for
      t.integer :high_danger_shots_for
      t.float :low_danger_x_goals_for
      t.float :medium_danger_x_goals_for
      t.float :high_danger_x_goals_for
      t.integer :low_danger_goals_for
      t.integer :medium_danger_goals_for
      t.integer :high_danger_goals_for
      t.float :score_adjusted_shots_attempts_for
      t.integer :unblocked_shot_attempts_for
      t.float :score_adjusted_unblocked_shot_attempts_for
      t.integer :d_zone_giveaways_for
      t.float :x_goals_from_x_rebounds_of_shots_for
      t.float :x_goals_from_actual_rebounds_of_shots_for
      t.float :rebound_x_goals_for
      t.float :total_shot_credit_for
      t.float :score_adjusted_total_shot_credit_for
      t.float :score_flurry_adjusted_total_shot_credit_for
      t.float :x_on_goal_against
      t.float :x_goals_against
      t.float :x_rebounds_against
      t.float :x_freeze_against
      t.float :x_play_stopped_against
      t.float :x_play_continued_in_zone_against
      t.float :x_play_continued_outside_zone_against
      t.float :flurry_adjusted_x_goals_against
      t.float :score_venue_adjusted_x_goals_against
      t.float :flurry_score_venue_adjusted_x_goals_against
      t.integer :shots_on_goal_against
      t.integer :missed_shots_against
      t.integer :blocked_shot_attempts_against
      t.integer :shot_attempts_against
      t.integer :goals_against
      t.integer :rebounds_against
      t.integer :rebound_goals_against
      t.integer :freeze_against
      t.integer :play_stopped_against
      t.integer :play_continued_in_zone_against
      t.integer :play_continued_outside_zone_against
      t.integer :saved_shots_on_goal_against
      t.integer :saved_unblocked_shot_attempts_against
      t.integer :penalties_against
      t.integer :penalty_minutes_against
      t.integer :face_offs_won_against
      t.integer :hits_against
      t.integer :takeaways_against
      t.integer :giveaways_against
      t.integer :low_danger_shots_against
      t.integer :medium_danger_shots_against
      t.integer :high_danger_shots_against
      t.float :low_danger_x_goals_against
      t.float :medium_danger_x_goals_against
      t.float :high_danger_x_goals_against
      t.integer :low_danger_goals_against
      t.integer :medium_danger_goals_against
      t.integer :high_danger_goals_against
      t.float :score_adjusted_shots_attempts_against
      t.integer :unblocked_shot_attempts_against
      t.float :score_adjusted_unblocked_shot_attempts_against
      t.integer :d_zone_giveaways_against
      t.float :x_goals_from_x_rebounds_of_shots_against
      t.float :x_goals_from_actual_rebounds_of_shots_against
      t.float :rebound_x_goals_against
      t.float :total_shot_credit_against
      t.float :score_adjusted_total_shot_credit_against
      t.float :score_flurry_adjusted_total_shot_credit_against

      t.timestamps
    end
  end
end
