class CreateTeamStats < ActiveRecord::Migration[8.0]
  def change
    create_table :team_stats do |t|
      t.references :team, null: false, foreign_key: true
      t.references :season, null: false, foreign_key: true
      t.string :name, null: false, default: ""
      t.string :position, null: false, default: ""
      t.string :situation, null: false, default: ""
      t.integer :games_played, null: false, default: 0
      t.float :x_goals_percentage, null: false, default: 0.0
      t.float :corsi_percentage, null: false, default: 0.0
      t.float :fenwick_percentage, null: false, default: 0.0
      t.float :ice_time, null: false, default: 0.0
      t.float :x_on_goal_for, null: false, default: 0.0
      t.float :x_goals_for, null: false, default: 0.0
      t.float :x_rebounds_for, null: false, default: 0.0
      t.float :x_freeze_for, null: false, default: 0.0
      t.float :x_play_stopped_for, null: false, default: 0.0
      t.float :x_play_continued_in_zone_for, null: false, default: 0.0
      t.float :x_play_continued_outside_zone_for, null: false, default: 0.0
      t.float :flurry_adjusted_x_goals_for, null: false, default: 0.0
      t.float :score_venue_adjusted_x_goals_for, null: false, default: 0.0
      t.float :flurry_score_venue_adjusted_x_goals_for, null: false, default: 0.0
      t.integer :shots_on_goal_for, null: false, default: 0
      t.integer :missed_shots_for, null: false, default: 0
      t.integer :blocked_shot_attempts_for, null: false, default: 0
      t.integer :shot_attempts_for, null: false, default: 0
      t.integer :goals_for, null: false, default: 0
      t.integer :rebounds_for, null: false, default: 0
      t.integer :rebound_goals_for, null: false, default: 0
      t.integer :freeze_for, null: false, default: 0
      t.integer :play_stopped_for, null: false, default: 0
      t.integer :play_continued_in_zone_for, null: false, default: 0
      t.integer :play_continued_outside_zone_for, null: false, default: 0
      t.integer :saved_shots_on_goal_for, null: false, default: 0
      t.integer :saved_unblocked_shot_attempts_for, null: false, default: 0
      t.integer :penalties_for, null: false, default: 0
      t.integer :penalty_minutes_for, null: false, default: 0
      t.integer :face_offs_won_for, null: false, default: 0
      t.integer :hits_for, null: false, default: 0
      t.integer :takeaways_for, null: false, default: 0
      t.integer :giveaways_for, null: false, default: 0
      t.integer :low_danger_shots_for, null: false, default: 0
      t.integer :medium_danger_shots_for, null: false, default: 0
      t.integer :high_danger_shots_for, null: false, default: 0
      t.float :low_danger_x_goals_for, null: false, default: 0.0
      t.float :medium_danger_x_goals_for, null: false, default: 0.0
      t.float :high_danger_x_goals_for, null: false, default: 0.0
      t.integer :low_danger_goals_for, null: false, default: 0
      t.integer :medium_danger_goals_for, null: false, default: 0
      t.integer :high_danger_goals_for, null: false, default: 0
      t.float :score_adjusted_shots_attempts_for, null: false, default: 0.0
      t.integer :unblocked_shot_attempts_for, null: false, default: 0
      t.float :score_adjusted_unblocked_shot_attempts_for, null: false, default: 0.0
      t.integer :d_zone_giveaways_for, null: false, default: 0
      t.float :x_goals_from_x_rebounds_of_shots_for, null: false, default: 0.0
      t.float :x_goals_from_actual_rebounds_of_shots_for, null: false, default: 0.0
      t.float :rebound_x_goals_for, null: false, default: 0.0
      t.float :total_shot_credit_for, null: false, default: 0.0
      t.float :score_adjusted_total_shot_credit_for, null: false, default: 0.0
      t.float :score_flurry_adjusted_total_shot_credit_for, null: false, default: 0.0
      t.float :x_on_goal_against, null: false, default: 0.0
      t.float :x_goals_against, null: false, default: 0.0
      t.float :x_rebounds_against, null: false, default: 0.0
      t.float :x_freeze_against, null: false, default: 0.0
      t.float :x_play_stopped_against, null: false, default: 0.0
      t.float :x_play_continued_in_zone_against, null: false, default: 0.0
      t.float :x_play_continued_outside_zone_against, null: false, default: 0.0
      t.float :flurry_adjusted_x_goals_against, null: false, default: 0.0
      t.float :score_venue_adjusted_x_goals_against, null: false, default: 0.0
      t.float :flurry_score_venue_adjusted_x_goals_against, null: false, default: 0.0
      t.integer :shots_on_goal_against, null: false, default: 0
      t.integer :missed_shots_against, null: false, default: 0
      t.integer :blocked_shot_attempts_against, null: false, default: 0
      t.integer :shot_attempts_against, null: false, default: 0
      t.integer :goals_against, null: false, default: 0
      t.integer :rebounds_against, null: false, default: 0
      t.integer :rebound_goals_against, null: false, default: 0
      t.integer :freeze_against, null: false, default: 0
      t.integer :play_stopped_against, null: false, default: 0
      t.integer :play_continued_in_zone_against, null: false, default: 0
      t.integer :play_continued_outside_zone_against, null: false, default: 0
      t.integer :saved_shots_on_goal_against, null: false, default: 0
      t.integer :saved_unblocked_shot_attempts_against, null: false, default: 0
      t.integer :penalties_against, null: false, default: 0
      t.integer :penalty_minutes_against, null: false, default: 0
      t.integer :face_offs_won_against, null: false, default: 0
      t.integer :hits_against, null: false, default: 0
      t.integer :takeaways_against, null: false, default: 0
      t.integer :giveaways_against, null: false, default: 0
      t.integer :low_danger_shots_against, null: false, default: 0
      t.integer :medium_danger_shots_against, null: false, default: 0
      t.integer :high_danger_shots_against, null: false, default: 0
      t.float :low_danger_x_goals_against, null: false, default: 0.0
      t.float :medium_danger_x_goals_against, null: false, default: 0.0
      t.float :high_danger_x_goals_against, null: false, default: 0.0
      t.integer :low_danger_goals_against, null: false, default: 0
      t.integer :medium_danger_goals_against, null: false, default: 0
      t.integer :high_danger_goals_against, null: false, default: 0
      t.float :score_adjusted_shots_attempts_against, null: false, default: 0.0
      t.integer :unblocked_shot_attempts_against, null: false, default: 0
      t.float :score_adjusted_unblocked_shot_attempts_against, null: false, default: 0.0
      t.integer :d_zone_giveaways_against, null: false, default: 0
      t.float :x_goals_from_x_rebounds_of_shots_against, null: false, default: 0.0
      t.float :x_goals_from_actual_rebounds_of_shots_against, null: false, default: 0.0
      t.float :rebound_x_goals_against, null: false, default: 0.0
      t.float :total_shot_credit_against, null: false, default: 0.0
      t.float :score_adjusted_total_shot_credit_against, null: false, default: 0.0
      t.float :score_flurry_adjusted_total_shot_credit_against, null: false, default: 0.0

      t.timestamps
    end
    add_index :team_stats, [:team_id, :season_id], unique: true
  end
end
